services:
  - postgres:9.4

variables:
  POSTGRES_DB: "maarchRM"
  POSTGRES_USER: maarch
  POSTGRES_PASSWORD: ""
  npm_config_cache: /builds/cypress-io/cypress-example-docker-gitlab/.npm
  CYPRESS_CACHE_FOLDER:  ~/.cache/Cypress


stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

job_build_php-7.3:
  image: php:7.3-apache
  stage: build
  before_script:
    - apt-get update > /dev/null
    - mkdir -p /usr/share/man/man1
    - mkdir -p /usr/share/man/man7
    - apt-get install cron -yqq > /dev/null
    - apt-get install libreoffice -yqq > /dev/null
    - bash ci/docker_install_php.sh > /dev/null
    - bash ci/docker_install_database.sh > /dev/null
  script:
    - useradd -m -g www-data maarch
    - export APACHE_RUN_USER=maarch
    - mkdir -p /var/www/html/
    - cp -R /builds/maarch/maarchRM/ /var/www/maarchRM/
    - mv /var/www/maarchRM/ /var/www/laabs/
    - cd /var/www/laabs
    - cp data/maarchRM/conf/vhost.conf.default data/maarchRM/conf/vhost.conf
    - cp data/maarchRM/conf/configuration.ini.default data/maarchRM/conf/configuration.ini
    - cp data/maarchRM/conf/confvars.ini.default data/maarchRM/conf/confvars.ini
    - >
      sed -i -e 's"baseUrl" : "http://maarchrm"!"baseUrl" : "http://localhost"!' /var/www/laabs/cypress.json
    - mkdir -p /var/www/laabs/data/maarchRM/repository/archives_1 /var/www/laabs/data/maarchRM/repository/archives_2
    - chown -R maarch:www-data /var/www
    - chmod -R 775 /var/www
    - cd /etc/apache2/sites-available/
    - touch maarchRM.conf
    - echo "Include /var/www/laabs/data/maarchRM/conf/vhost.conf" >> maarchRM.conf
    - a2ensite maarchRM.conf
    - a2dissite 000-default.conf
    - a2enmod rewrite
    - a2enmod env
    - service apache2 start
    - curl --location -s --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-7.phar
    - chmod +x /usr/local/bin/phpunit
  except:
    - master

functional-test:cypress-e2e:
  image: cypress/base:10
  stage: test
  script:
    - $(npm bin)/cypress install
    - $(npm bin)/cypress verify
    - $(npm bin)/cypress run
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
