#services:
#  - docker:dind

stages:
  - tests
  - push

variables:
  npm_config_cache: /builds/cypress-io/cypress-example-docker-gitlab/.npm
  CYPRESS_CACHE_FOLDER: /builds/cypress-io/cypress-example-docker-gitlab/cache/Cypress

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

functional-test:cypress:
  image: cypress/base:10
  stage: tests
  script:
    - npm ci
    - $(npm bin)/cypress verify
    - $(npm bin)/cypress run
  only:
    - schedules
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos

php-metrics:
  image: jakzal/phpqa
  stage: tests
  script: phpmetrics --report-html=var/php-metrics src
  artifacts:
    paths:
      - var/php-metrics/
  allow_failure: true

php-phpmd:
  image: jakzal/phpqa
  stage: tests
  script: phpmd src html phpmd.xml --reportfile var/phpmd.html
  artifacts:
    paths:
      - var/phpmd.html
  allow_failure: true

php-deprecation-detector:
  image: jakzal/phpqa
  stage: tests
  script:
    - deprecation-detector check src vendor/
  allow_failure: true

php-cs-fixer:
  image: jakzal/phpqa
  stage: tests
  script:
    - ./php-cs-fixer.sh
  artifacts:
    paths:
      - var/patch.diff
    expire_in: 24 hrs
    when: on_failure
  allow_failure: true


#build-dockerhub:
#  stage: push
#  script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#    - docker build dockerfile/version/ -t "$CI_REGISTRY_IMAGE"
#    - docker push "$CI_REGISTRY_IMAGE"
#  only:
#    - feat/gitlab_ci
#  except:
#    - schedules