services:
  - postgres:9.4

variables:
  POSTGRES_DB: "maarchRM"
  POSTGRES_USER: maarch
  POSTGRES_PASSWORD: ""

stages:
  - test

before_script:
  - apt-get update > /dev/null
  - mkdir -p /usr/share/man/man1
  - mkdir -p /usr/share/man/man7
  - apt-get install cron -yqq > /dev/null
  - apt-get install libreoffice -yqq > /dev/null
  - bash ci/docker_install_php.sh > /dev/null
  - bash ci/docker_install_database.sh > /dev/null

job_php-7.3:
  image: php:7.3-apache
  stage: test
  script:
    - mkdir -p /var/www/html/
    - cp -R /builds/maarch/maarchRM/ /var/www/maarchRM/
    - mv /var/www/maarchRM/ /var/www/laabs/
    - cd /var/www/laabs
    - curl --location -s --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-7.phar
    - chmod +x /usr/local/bin/phpunit
    - phpunit --coverage-text --colors=never -c phpunit.xml
  only:
    - feat/gitlab_ci
